services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/raw;
      mc mb -p local/clean;
      mc mb -p local/curated;
      exit 0;
      "

  validations:
    build:
      context: ./validations
      dockerfile: Dockerfile
    container_name: validations
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=hackathon
      - VALIDATION_SERVICE_URL=http://validations:8000/data-validation
      - DATA_LAKE_ENABLED=true
      - DATA_LAKE_ENDPOINT=minio:9000
      - DATA_LAKE_ACCESS_KEY=minioadmin
      - DATA_LAKE_SECRET_KEY=minioadmin
      - DATA_LAKE_SECURE=false
      - RAW_BUCKET=raw
      - CLEAN_BUCKET=clean
      - CURATED_BUCKET=curated
    depends_on:
      - mongodb
      - validations
      - minio
      - minio-init

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=200
      - VITE_HMR_CLIENT_PORT=5173
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  mongo_data:
  minio_data:
  frontend_node_modules:
