services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  validations:
    build:
      context: ./validations
      dockerfile: Dockerfile
    container_name: validations
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=hackathon
      - VALIDATION_SERVICE_URL=http://validations:8000/data-validation
    depends_on:
      - mongodb
      - validations

volumes:
  mongo_data:
